deploy shows playwright result (#609)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -127,10 +127,10 @@ jobs:
           echo "dspace healthcheck:"
           docker exec $DNAME /bin/bash -c "cd /dspace/bin && ./dspace healthcheck -v"
 
-  trigger-playwright:
+  playwright-after-deploy8:
     runs-on: ubuntu-latest
-    needs: [deploy-5, deploy-8]
-    if: ${{ always() }}
+    needs: deploy-8
+    if: '!inputs.IMPORT'
     steps:
       - name: run playwright
         run: |
@@ -139,4 +139,54 @@ jobs:
           --request POST \
           https://api.github.com/repos/dataquest-dev/\
           dspace-ui-tests/actions/workflows/cron-test.yml/dispatches \
-          --data "{\"ref\":\"refs/heads/master\"}"
+          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+
+          # wait for it to start
+          sleep 30s
+
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+           RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
+
+          echo $RES
+          # if last result is not success, return -1 and fail
+          if [[ $RES != 'success' ]]; then
+            exit 1
+          fi;
+
+  playwright-after-import8:
+    runs-on: ubuntu-latest
+    needs: import-8
+    if: inputs.IMPORT
+    steps:
+      - name: run playwright
+        run: |
+          curl -H "Accept: application/vnd.github.everest-preview+json" \
+          -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
+          --request POST \
+          https://api.github.com/repos/dataquest-dev/\
+          dspace-ui-tests/actions/workflows/cron-test.yml/dispatches \
+          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+
+          # wait for it to start
+          sleep 30s
+
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+           RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-ui-tests/actions/workflows/cron-test.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
+
+          echo $RES
+          # if last result is not success, return -1 and fail
+          if [[ $RES != 'success' ]]; then
+            exit 1
+          fi;
