Internal/rest test after deploy (#615)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -160,9 +160,43 @@ jobs:
           echo $RES
           # if last result is not success, return -1 and fail
           if [[ $RES != \"success\" ]]; then
-            echo "playwright tests failed! check appropriate action run"
+            echo "playwright tests have failed! check appropriate action run"
             exit 1
           fi;
+
+  rest-tests-after-deploy8:
+    runs-on: ubuntu-latest
+    needs: playwright-after-deploy8
+    timeout-minutes: 15
+    steps:
+      - name: run rest-tests
+        run: |
+          curl -H "Accept: application/vnd.github.everest-preview+json" \
+          -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
+          --request POST \
+          https://api.github.com/repos/dataquest-dev/\
+          dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
+          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+
+          # wait for it to start
+          sleep 30s
+
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+            RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
+
+          echo $RES
+          # if last result is not success, return -1 and fail
+          if [[ $RES != \"success\" ]]; then
+            echo "rest-tests have failed! check appropriate action run"
+            exit 1
+          fi;
+
 
   playwright-after-import8:
     runs-on: ubuntu-latest
@@ -197,6 +231,40 @@ jobs:
           echo $RES
           # if last result is not success, return -1 and fail
           if [[ $RES != \"success\" ]]; then
-            echo "playwright tests failed! check appropriate action run"
+
+            echo "playwright tests have failed! check appropriate action run"
+            exit 1
+          fi;
+
+  rest-tests-after-import8:
+    runs-on: ubuntu-latest
+    needs: playwright-after-import8
+    timeout-minutes: 15
+    steps:
+      - name: run rest-tests
+        run: |
+          curl -H "Accept: application/vnd.github.everest-preview+json" \
+          -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" \
+          --request POST \
+          https://api.github.com/repos/dataquest-dev/\
+          dspace-rest-test/actions/workflows/run_unittests.yml/dispatches \
+          --data "{\"ref\":\"refs/heads/master\"}" 2> /dev/null
+
+          # wait for it to start
+          sleep 30s
+
+          # get result of last job
+          RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+
+          # while job did not finish, sleep
+          while [[ $RES == 'null' ]]; do
+            sleep 10s
+            RES=$(curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}" https://api.github.com/repos/dataquest-dev/dspace-rest-test/actions/workflows/run_unittests.yml/runs?per_page=1 2> /dev/null | jq .workflow_runs[0].conclusion)
+          done;
+
+          echo $RES
+          # if last result is not success, return -1 and fail
+          if [[ $RES != \"success\" ]]; then
+            echo "rest-tests have failed! check appropriate action run"
             exit 1
           fi;
